// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnR9NKNsKJSZ1LUxjAdXEctdA8agjVqZM',
    appId: '1:372550702977:web:98cbedd17ef04069a47a80',
    messagingSenderId: '372550702977',
    projectId: 'ulmo-ce75c',
    authDomain: 'ulmo-ce75c.firebaseapp.com',
    storageBucket: 'ulmo-ce75c.firebasestorage.app',
    measurementId: 'G-SZX5K09881',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8rStGpBxf9XDUCoHaTBJFEQNj9VO9kI',
    appId: '1:372550702977:android:d7699c3f26fb4c8ca47a80',
    messagingSenderId: '372550702977',
    projectId: 'ulmo-ce75c',
    storageBucket: 'ulmo-ce75c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeyXyk5QitZf6jE_ZMpk3sn81MLggOpA0',
    appId: '1:372550702977:ios:24bf8ac69763d80ea47a80',
    messagingSenderId: '372550702977',
    projectId: 'ulmo-ce75c',
    storageBucket: 'ulmo-ce75c.firebasestorage.app',
    iosBundleId: 'com.example.ulmo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeyXyk5QitZf6jE_ZMpk3sn81MLggOpA0',
    appId: '1:372550702977:ios:24bf8ac69763d80ea47a80',
    messagingSenderId: '372550702977',
    projectId: 'ulmo-ce75c',
    storageBucket: 'ulmo-ce75c.firebasestorage.app',
    iosBundleId: 'com.example.ulmo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnR9NKNsKJSZ1LUxjAdXEctdA8agjVqZM',
    appId: '1:372550702977:web:0f74d8a2d994ac7aa47a80',
    messagingSenderId: '372550702977',
    projectId: 'ulmo-ce75c',
    authDomain: 'ulmo-ce75c.firebaseapp.com',
    storageBucket: 'ulmo-ce75c.firebasestorage.app',
    measurementId: 'G-E39B20HFRV',
  );
}
